### PR TITLE
Edit wercker hipchat notification

### PR DESCRIPTION
**Pull request by RongxinZhang**
-  [x] custom hipchat notification message.
-  [x] change token in wercker
-  [x] added badges

### CODE REVIEW

**Comment by RongxinZhang** [comment]
@wired8  @Jkhwan plz review

**Comment by wired8** [comment]
:+1:

**Comment by Jkhwan** [comment]
:+1:

**Comment by RongxinZhang** [comment]
reference: https://github.com/Retsly/api/pull/1294

**Pull request merged**
