### PR TITLE
Emit 'ServerDown' when session ajax call errors with no response text

### PR DESCRIPTION
**Pull request by switters**
#### Team
Project Lead: @switters
Code Review: @slajax @lvivier 
Deployment Review: @slajax 

#### Synopsis
We need a way to know when the retsly-js-sdk cannot contact the server. A distinguishing feature of the error that occurs on an ajax call to a downed retsly server is that there is no responseText -- a property that occurs during normal, server-up errors.

#### Requirements:
- [x] Emit an event during session call to retsly when the request errors with no responseText
- [x] Retsly.ready() should handle errors.

##### Testing Setup
- [x] This is a sister PR to Retsly/www @ switters/453. Checkout this branch and build www.

##### Pass Requirements
- [ ] Shut down api and make a request. Splash screen should show.
- [ ] Restart api server. www should reconnect.

##### Post-Deploy Steps
- [ ] Release new version of sdk
- [ ] Ensure www @ switters/463 refs new sdk release

#### Screenshot
image

### CODE REVIEW

**Comment by switters** [comment]
@lvivier @slajax - review changes to retsly-js-sdk?

**Comment by lvivier** [comment]
@slajax ping

This looks good to me for the most part. Also, should this new event be added to the SDK docs?

**Comment by slajax** [comment]
Yes, it would be a good idea to update the readme with these changes.

**Comment by switters** [comment]
@slajax @lvivier - Will update readme (and also cover null case -- wat).

**Comment by switters** [comment]
@lvivier -- null case handled. @slajax On reviewing the readme, I found that there is no information whatsoever on events emitted by the retsly-js-sdk -- readme.md still references the use of sockets and looks to be a re-write, which is out of this issues scope.

**Comment by lvivier** [comment]
:+1: from me, maybe there's an opportunity to improve the docs on this?

**Comment by slajax** [comment]
You can tag and merge now!

**Pull request merged**
